name: CD_PUSH

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Haskell
        uses: haskell-actions/setup@v2

      - name: Install Dependencies
        run: stack build --only-dependencies

      - name: Build using Stack
        run: stack build
      
      - name: Test using Stack
        run: stack test

  check_commits_convention:
    name: Conventional Commits Message
    runs-on: ubuntu-latest
    steps:
      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(?:feat|fix|chore|test|docs|build|ci|style|refactor|perf|revert)(?:\(\w+\))?:\s[a-z]{1,2}.+'
          error: 'The commit message must have the following structure: <type>(?): <description>'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  check_branches_convention:
    name: Conventional Branches Name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z]+)/([a-z]+)'
          allowed_prefixes: 'stable,fix,chore,docs,feat,build,ci,refactor,perf,hotfix'
          ignore: main,develop
          min_length: 4
          max_length: 100
